# Generated by Django 2.1.2 on 2018-10-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_and_chapters', '0002_auto_20181008_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_and_chapters.Book'),
        ),
    ]
